### ISSUE TITLE
How to hide webpack output result table ?

### ISSUE THREAD

**Issue by fvsadem** [laravel-mix/laravel-mix#2764]
-   Laravel Mix Version: 6.0.6
-   Node Version: 14.15.4
-   NPM Version: 6.13.7
-   Webpack Version: 5.11.1
-   cross-env Version: 7.0.3
-   OS: Windows 10

Hi,

When i build for production with the command below, i have the webpack results in a table.
``npm run production``
Where script is:
 ``cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --config=node_modules/laravel-mix/setup/webpack.config.js``
 
How could i hide the table below and just show "Compiled Successfully in xxxx ms"

```                        
   Laravel Mix v6.0.6   
                        

✔ Compiled Successfully in 13063ms
┌───────────────────────────────────┬──────────┐
│ File                              │ Size     │
├───────────────────────────────────┼──────────┤
│ fonts/vendor/@fortawesome/fontaw… │ 896 KiB  │
├───────────────────────────────────┼──────────┤
│ fonts/vendor/@fortawesome/fontaw… │ 730 KiB  │
├───────────────────────────────────┼──────────┤
│ /js/app.js                        │ 310 KiB  │
├───────────────────────────────────┼──────────┤
│ css/app.css                       │ 290 KiB  │
├───────────────────────────────────┼──────────┤
................................

```

Thanks for you help

**Comment by JeffreyWay** [comment]
I don't think we currently expose an option to hide that. You're the only person I've seen request it, so I'm not sure it's overly necessary.

**Comment by 0x6d617474** [comment]
We have a logging function in our CI/CD process which has a fairly low limit on the number of bytes it stores, so having the option to disable the output table at the end would be very helpful in that case, since otherwise errors later in the CI process get hidden because the table takes up a lot of space. 

In Mix 5 the output was hidden in our production deployments, and I was sad to see no option to disable it in 6.

**Comment by isotrope** [comment]
I might be the second person.

I have two .copy() processes in my build.
That means that I end up with a table that's about two screens-high of image filenames.

The previous version discarded this information and I only saw the affected files.
( It also did a clear so it was more of a status panel )

Can I, at the very least, choose "which processes" to exclude from that table? 
It also doesn't say "when" it concluded so I'm never sure which of the humongous lists were the last ones when trying to scroll up (because of the lack of clearing the terminal).

**Comment by lk77** [comment]
Hello,

same issue here, 

the new table is unusable,

**Comment by pabueco** [comment]
I had the same when using a package that copied a few hundred images to the public folder. Mix would just print every single file on every compilation. I invested some time since it was really annoying.

Turns out you can simply add an event hook and overwrite the assets object.
```js
mix.after((stats) => {
  stats.compilation.assets = {}
})
```
This however prevents mix from displaying any files. 
If you only want to remove unimportant files like images you can just do this.
```js
mix.after((stats) => {
  const assets = { ...stats.compilation.assets }
  stats.compilation.assets = {}

  for (const [path, asset] of Object.entries(assets)) {
    if (path.endsWith('.js')) {
      stats.compilation.assets[path] = asset
    }
  }
})
```
Since you get the whole target path of the asset you can also filter them based on their destinationfolder or use a regex to apply a more complex filter logic.

**Comment by thecrypticace** [comment]
I'm gonna re-open this. I think showing 100s of files is overkill and we need at least some way to filter them. Also we need to investigate if we can show only changed files when watching.

**Comment by thecrypticace** [comment]
I won't have the time to put forth to this today (maybe this week?) but we'd definitely welcome a PR and I'll be more than happy to help whoever work through it.

**Comment by jakedowns** [comment]
as an odd side-request, i'd love the ability to disable the output from "clearing" the terminal window as it prints

in my example, i use `concurrently` to run some separate webpack routines. when the output is cleared, i lose track of errors within sub processes, and have to run them one by one to see what errored.

**Comment by aroy314** [comment]
Thanks for the hint about hiding result table + not clearing console 🙌 

Do you know if there is a way to hide the blue label "Laravel Mix v6.0.49" displayed after each compilation ? I looked into the `src/config.js` but found nothing. 

Thanks

![image](https://user-images.githubusercontent.com/14325646/178244890-4db7dd65-fa5c-4ff1-abb8-4d689a3f6c93.png)

**Comment by Freezon** [comment]
@aroy314, hope it helps: [Laravel Mix Simple Output Plugin](https://www.npmjs.com/package/laravel-mix-simple-output)

**Comment by fvsadem** [comment]
@Freezon  Thank you !
This is exactly what i need ;)
