### ISSUE TITLE
sh: 1: mix: not found

### ISSUE THREAD

**Issue by SamKani92** [laravel-mix/laravel-mix#2903]
Mix: Tried multiple 6,0 versions.
Node: 12.19.0
NPM: 7.6.3
OS: Windows 10

Once again I am having issues with a new version of Laravel Mix.

`npm run watch-poll` throws a "sh: 1: mix: not found" error.

Fresh Laravel 8.12 installation. Don't have any colons in the folder name, Have tried deleting node_modules, clearing cache and reinstalling via both NPM and Yarn. Have tried updating Laravel Mix to the latest versions.

I'm using --no-bin-links because npm install never works without it.

Laravel 7 and Mix 5 work perfectly fine, in fact after Laravel 8 failed I tried a fresh Laravel 7 installation and had no issues.

```
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "mix",
        "watch": "mix watch",
        "watch-poll": "mix watch -- --watch-options-poll=1000",
        "hot": "mix watch --hot",
        "prod": "npm run production",
        "production": "mix --production"
    },
    "devDependencies": {
        "axios": "^0.21",
        "laravel-mix": "^6.0.6",
        "lodash": "^4.17.19",
        "postcss": "^8.1.14"
    },
    "dependencies": {
        "bootstrap": "^5.0.0-beta2"
    }
}
```
```
const mix = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel applications. By default, we are compiling the CSS
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.js('resources/js/app.js', 'public/js')
    .sass('resources/sass/bootstrap.scss', 'public/css')
    .sass('resources/sass/app.scss', 'public/css')
    .version();
```

**Comment by lmeysel** [comment]
If I remember correctly, before mix 6 there was no `mix` command, therefore you maybe just did not encounter an underlaying problem. It is very likely that the problem is not mix specific. As your OS is Win 10 and the error comes from `sh` it seems you somehow messed up with WSL and cmd/powershell?

I know the issue in general and few of my problems in the past were:

- `npm install` with cmd/powershell but then `npm run ...` in WSL: The files created in node_modules/.bin are somehow not correct (I think it has to do with linux/windows links and shell-scripts)
- check whether `node_modules/.bin`  is created and you find a `mix` and `mix.cmd` and `mix.ps1` in it (after `npm i` from powershell)
- run `npx mix` on your console in your project root, see if that works

Another ugly issue I had was, that somehow node wanted to do something in global installed packages (even though I did install them locally). Then (in good dirty windows manner) there was a file path somewhere in my %USERPROFILE% directory, whereas my username was like "Firstname Lastname" which then caused problems due to the whitespace.

But as I said, to what you wrote that seem not to be mix-related.

**Comment by thecrypticace** [comment]
The above is correct:
1. If you `npm install` on Windows and NPM run in WSL it will not work.
2. If you use `--no-bin-links` the .bin folder will usually not be created thus making the npm scripts not work
3. Windows does not like whitespace in path names + NPM scripts. If you use yarn they've seemed to find a way to work around this problem. You can try using Yarn 1 and see if that also works around your problem.

**Comment by SlimGee** [comment]
I have the same problem in Kali Linux `node v12.21.0` `npm 7.5.2` and running `npx mix` throws `npm ERR! could not determine executable to run`

**Comment by Anaxarchos** [comment]
The first anwser here: [https://stackoverflow.com/questions/65718391/laravel-npm-command-mix-not-found/65720215#65720215](https://stackoverflow.com/questions/65718391/laravel-npm-command-mix-not-found/65720215#65720215) did work for me.

**Comment by green255** [comment]
This has to do with the no bin links on windows and the syntax of the new package.json file. I solved this by doing the following:

1. open up powershell as admin
1. navigate to project root
1. run this command
```
node c:\<path to node installation>\node_modules\npm\bin\npm-cli.js install --scripts-prepend-node-path=auto
```
Full answer here:
https://stackoverflow.com/a/67574817/1272667

**Comment by thecrypticace** [comment]
Closing as there's an answer / workaround.

**Comment by vedmant** [comment]
I have the same issue on MacOs, I use yarn. What's the right way to fix this?

**Comment by OneMohrTime** [comment]
I was able to get around this by bumping `laravel-mix`, `sass-loader`, and `webpack` to their latest versions, detailed here: https://stackoverflow.com/questions/65718391/laravel-npm-command-mix-not-found/65720215#65720215
