### ISSUE TITLE
BUG: tsconfig baseUrl / path does not work 

### ISSUE THREAD

**Issue by phatNfqAsia** [laravel-mix/laravel-mix#3081]
-   Laravel Mix Version: 6.0.27 (`npm list --depth=0`)
-   Node Version (`node -v`): 14.17.4
-   NPM Version (`npm -v`): 6.14.14
-   OS: Ubuntu 20.4

### Description:
I am setting up my repo to work with Typescript, which include a `tsconfig.json` file having:
```json
...
    "baseUrl": "resources/js",                                
    "paths": {
      "*": ["*"]
      },
...
```
And VsCode IDE does take this into consideration and give hint / load file properly. But when I run `mix`  (by `npm run dev`). It can not resolve the shortened relative path ('HookForm' instead of  '../../HookForm')

Currently I have  a workaround myself on this by editting `webpack.mix.js`:
```javascript
mix.webpackConfig({
        resolve: {
            modules: [
                'node_modules',
                path.resolve(__dirname, 'resources/js')
            ]
        }
    });
```
This does patch the problem I feel very sorry for the `tsconfig.json` for not working as expected. Please have a look, it is a pity that I can not share the repo because it is my company asset. But if you can not reproduce this problem from your side I am happy to create a sample repo :grin:

**Comment by thecrypticace** [comment]
This isn't a mix problem. When you have custom paths in a typescript config you have to set up custom resolution behavior / aliases in webpack as well. As far as I know there's no syncing between ts-loader / tsconfig paths and webpack's config which I believe is on purpose since they're not directly compatible options. For instance if you used a prefix of `@/` to mean the root dir you could achieve the above using `mix.alias({"@": path.resolve(__dirname, 'resources/js')})` but not with the implicit wildcard behavior you are using.

**Comment by phatNfqAsia** [comment]
@thecrypticace you are right, today I have a similar problem with Rollup too. Thanks!
