### ISSUE TITLE
process.env.MIX_ONBOARDING_URL variable is undefined

### ISSUE THREAD

**Issue by raimondas-nuz** [laravel-mix/laravel-mix#3108]
-   Laravel Mix Version: 6.0.31 (`npm list --depth=0`)
-   Node Version (`node -v`): 14.15.5
-   NPM Version (`npm -v`): 6.14.11
-   OS: Ubuntu

### Description:
I have a vue component that uses process.env.MIX_ONBOARDING_URL and locally it's working like a charm, but I started to migrate to serverless using Vapor and after deployment there is a "Ts.env.MIX_ONBOARDING_URL" instead of "http://example.com/" url.

I tried [https://github.com/laravel-mix/laravel-mix/issues/2782](url) and other closed issues related with .env variables picking.

Anyone could help with that? Thank you for your time in advance.

### Steps To Reproduce:
vapor.yml
```
build:
      - 'COMPOSER_MIRROR_PATH_REPOS=1 composer install'
      - 'php artisan event:cache'
      - 'npm ci && npm run production && rm -rf node_modules'
    deploy:
      - 'php artisan migrate --force'
```

webpack.mix.widget.js
```
const mix = require('laravel-mix');

mix.setPublicPath('public')
  .js('resources/js/widget/src/main.js', 'widget/widget.js').vue({
    version: 2,
    options: {
      shadowMode: true
    }
  });
```

main.js
```
import Vue from "vue";
import wrap from "@vue/web-component-wrapper";
import Widget from "./Widget.vue";

const wrappedElement = wrap(Vue, Widget);

window.customElements.define("widget", wrappedElement);
```

widget.js
```
<template>
    <iframe
        width="100%"
        height="100%"
        frameborder="0"
        :src="iframe.src"
        @load="load"
        v-show="iframe.loaded"
    >
    </iframe>
</template>

<script>
export default {
    data: function() {
        return {
            iframe: {
                src: process.env.MIX_ONBOARDING_URL + this.token,
                loaded: false
            },
            message: ''
        }
    },
    props: {
        token: {
            type: String,
            default: ''
        }
    },
    methods: {
        load: function() {
            this.iframe.loaded = true;
        }
    }
};
</script>
```

**Comment by raimondas-nuz** [comment]
Anyone?

**Comment by thecrypticace** [comment]
I don't have a lot of experience with Vapor so I'm not sure but if I find some time to play around with it soon I'll see what I can figure out.

**Comment by raimondas-nuz** [comment]
I added 

`console.log(process.env.MIX_ONBOARDING_URL);`

in my mix file. On local machine I see the proper url from .env file, in staging it is undefined.

**Comment by IronSinew** [comment]
There's a few options of things you can do here..

1. Commit a non-sensitive-data-only `.env.{environment}` file that will be automatically injected in by mix (because `.env` shouldn't be committed to the repo.
2. Use some service (like envault) to create the `.env` file during your CI process, but before you do the `npm ci && npm run production && rm -rf node_modules`
3. (Untested) Set env variables in your CI/CD that you inject into your mix arguments that are expected/handled like any other injected arguments.

I found that number 1 was the easiest thing to manage for non-sensitive data that you want to get into javascript/vue (because nothing sensitive should be injected into `process.env` ideally anyway.

**Comment by raimondas-nuz** [comment]
@IronSinew thank you a lot!
I don't know about 2 option, but 1 and 3 work. I chose third.
