### ISSUE TITLE
Error TS6133: '$props' | '$setup' | '$options' is declared but its value is never read when building Vue SFC

### ISSUE THREAD

**Issue by iraklisg** [laravel-mix/laravel-mix#3110]
-   Laravel Mix Version: 6.0.31
-   Node Version: 16.6.2
-   NPM Version: 7.20.3
-  Webpack Version: 5.53.0
-   OS: 5.10.63-1-MANJARO (Arch Linux)

### Description:

In a fresh Laravel installation I have installed typescript

```bash
npm i -D typescript ts-loader
```

My `tsconfig` file is the following
```
{
  "compilerOptions": {
    // Project options
    "lib": ["esnext", "dom"],
    "removeComments": true,
    "target": "esnext",
    "jsx": "preserve",

    // Strict checks
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,

    // Linter checks
    "noImplicitReturns": true,
    "noUncheckedIndexedAccess": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true, 

    // Module resolution
    "baseUrl": ".",
    "esModuleInterop": true,
    "moduleResolution": "node",
    "module": "esnext",
    "paths": {
      "@/*": ["resources/js/*"]
    },
  },
  "include": [
    "resources/js/**/*.ts",
    "resources/js/**/*.tsx",
    "resources/js/**/*.vue"
  ],
  "exclude": [
    "node_modules"
  ],
}
```

My `webpack.mix.js file` is the following:

```
const mix = require('laravel-mix');
const path = require('path');


mix.alias({
    '@': path.join(__dirname, 'resources/js')
});

mix.ts('resources/js/app.ts', 'public/js').vue({ runtimeOnly: true }

```

My entrypoint (renamed to `app.ts`):

```
import { createApp } from 'vue';

import Hello from '@/components/Hello.vue';
const app = createApp({});

app.component('Hello', Hello);

app.mount('#app');
```

I have created the following Vue SFC

```
<script lang=ts>
import { ref, defineComponent } from 'vue'

export default defineComponent({
  name: "Foo",
  props: {
    myProp: {
      type: String,
      default: 'Hello'
    }
  },
  setup(props) {
    const msg = ref(props.myProp);
    
    return { msg }
  }
})
</script>

<template>
  <h1>{{ msg }}</h1>
  <input v-model="msg">
</template>
```

When I try to build my app I am getting the following errors

```
ERROR in /home/node/app/resources/js/components/ApplicationCreateForm.vue.ts(10,46)
      TS6133: '$props' is declared but its value is never read.
ERROR in /home/node/app/resources/js/components/ApplicationCreateForm.vue.ts(10,46)
      TS6133: '$setup' is declared but its value is never read.
```

*Before upgrading* the `node_modules` to vue 3.2.16 and ts-loader 9.2 I was able to build my app without problems using this tsconfig but *after upgrading* these errors came up. 

I can suppress the errors by setting the `noUnusedParameters` option to `false` but I don't feel that this should be the solution

### Steps to reproduce

1. Clone this repo https://github.com/iraklisg/vue-typescript
2. Run `npm run dev`

As stated in https://github.com/vuejs/vue-next/issues/4668#issuecomment-926687181 the following behavior also occurs
> The error happens when I run npm run dev,
> but doesn't happen when I run yarn dev, even though that runs the same script.
> but when I directly run yarn mix (which yarn dev runs as well), the errors show up and the build fails.

**Comment by thecrypticace** [comment]
It is very unlikely this is related to mix but I'll poke around to see what I can figure out

**Comment by thecrypticace** [comment]
This consistently happens regardless of package manager used to install or run the scripts. It also happens when invoking mix directly using `./node_modules/.bin/mix`. There was one case I saw where it did not happen. I cannot reliably reproduce the situation however which leads me to believe it's possibly a race condition in ts-loader causing it to not report errors in some instances.

**In any case this has nothing to do with Mix.**

The errors happen because of two things:

1. You have your project configured to error on unused function parameters: https://github.com/iraklisg/vue-typescript/blob/4496628ba4aeb44d42b720c5c0a9deddde232cab/tsconfig.json#L18

2. Vue SFCs in certain formats result in compiled code with unused arguments intended to be stripped by a production build process: https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8aDE+dGVzdDwvaDE+XG48L3RlbXBsYXRlPlxuPHNjcmlwdD5cbi8vIHN0dWZmXG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vc2ZjLnZ1ZWpzLm9yZy92dWUucnVudGltZS5lc20tYnJvd3Nlci5qc1wiXG4gIH1cbn0ifQ==

In this case the inclusion of a non-empty `<script>` tag results in the unused parameters being added to the render function while a `<script setup>` block does not appear to produce the same results.
