### ISSUE TITLE
mix.postCss() is executed before .sass() compilation is done

### ISSUE THREAD

**Issue by alexanderaeppli** [laravel-mix/laravel-mix#3218]
-   Laravel Mix Version: 6.0.42 
-   Node Version: v17.5.0
-   NPM Version: 8.4.1
-   OS: MacOS Monterey 12.2.1, Fedora 34 ARM64 (VM)

### Description:
When trying to apply .postCss() to a css file generated by .sass(), the file can't be found even though it was successfully generated. On the next run, compilation works but postCss uses the old app.css file created by the prior run.

### Steps To Reproduce:
Run mix with this webpack.mix.js
```js
const mix        = require('laravel-mix');
const PrefixWrap = require('postcss-prefixwrap');

mix.sass('resources/scss/app.scss', 'assets/css')
    .postCss('assets/css/app.css', 'assets/css/app.css', [
        PrefixWrap('.dcwiStyles', {
            ignoredSelectors: [':root']
        })
    ])
```

### Workaround
If you provide a postcss.config.js file and omit .postcss() in webpack.mix.js compilation and postCSS work as intended.

**Comment by thecrypticace** [comment]
Mix steps are not executed in serial order — they happen all at one time (as much as possible anyway). This is expected behavior.

For your use case you can either:

1. Use a `postcss.config.js` file — I prefer this one personally since it's consistent with how PostCSS is used with other tools.

2. Set a list of global postcss plugins:

```js
const mix  = require('laravel-mix')
const PrefixWrap = require('postcss-prefixwrap')

mix.sass('resources/scss/app.scss', 'assets/css')
mix.options({
  postCss: [
    PrefixWrap('.dcwiStyles', {
      ignoredSelectors: [':root'],
    }),
  ],
})
```

3. Pass a fourth argument to `mix.sass()` with your list of postcss plugins:
```js
const mix  = require('laravel-mix')
const PrefixWrap = require('postcss-prefixwrap')

mix.sass('resources/scss/app.scss', 'assets/css', {}, [
  PrefixWrap('.dcwiStyles', {
    ignoredSelectors: [':root'],
  }),
])
```

**Comment by alexanderaeppli** [comment]
That makes sense. Thanks for the help!
