### ISSUE TITLE
Only last defined PostCSS config is used

### ISSUE THREAD

**Issue by titantwentyone** [laravel-mix/laravel-mix#3226]
-   Laravel Mix Version: 6.0.43
-   Node Version (`node -v`): 17.01
-   NPM Version (`npm -v`): 8.1.0
-   OS: Ubuntu Mate

### Description:
I believe that this is related in some part to #2357. When configuring different css files to generate from sass with different postcss configs, it seems only the last postcss config is used.

### Steps To Reproduce:
I have created a minimum reproduction case at https://github.com/titantwentyone/mix-issue-mar-2022. In this instance, both generated files include the class `bg-anothertest` when only `anothertest.css` should (IMO) and `test.css` should include `bg-test` but doesn't.

I guess the simplest solution is to create two `webpack.mix.js` configs but wondered if this should just work as per my example?

**Comment by thecrypticace** [comment]
Chaining calls in Laravel Mix does not work this way. `mix.options` sets them for the entire build.

`mix.whatever().whatever2().whatever3()` is equivalent to `mix.whatever(); mix.whatever2(); mix.whatever3()` no matter what the command is. There is *one* exception: `mix.inProduction()` which returns a boolean instead of something you can chain with.

Your config is the same as:

```js
mix.sass('./src/test.scss', './dist')
mix.sass('./src/anothertest.scss', './dist')
mix.options({
  postCss: [tailwindcss('./tailwind.config.js')]
})

mix.options({
  postCss: [tailwindcss('./anothertest.tailwind.config.js')]
})
```

which calls mix.options twice overwriting the postcss config. This is a "global" postcss config.

Instead, what you want is to pass the postcss plugins to each sass command:

```js
mix.sass('./src/test.scss', './dist', {}, [
  tailwindcss('./tailwind.config.js'),
])

mix.sass('./src/anothertest.scss', './dist', {}, [
  tailwindcss('./anothertest.tailwind.config.js')
])
```

**Comment by titantwentyone** [comment]
Thank you!
