### ISSUE TITLE
what is the future of laravel-mix?

### ISSUE THREAD

**Issue by jaxramus** [laravel-mix/laravel-mix#3297]
this is not a bug but there is no discussions tab in this repo

i am curious what the future of mix is, given that laravel has moved to vite

to be honest, i think mix is vastly superior to vite, but thats just my opinion

what is the future of mix?

**Comment by thecrypticace** [comment]
A large portion of the ecosystem has/is/will be moving to Vite however there's still a spot for Laravel Mix for projects that need it. Including a lot of non-Laravel projects that happen to use Mix. So, not Mix isn't going anywhere. I can't speak to plans for the the far future but I plan on keeping it updated where possible/feasible and upgrading it to webpack 6 whenever that becomes a thing in the future.

Now, I definitely don't give Mix the attention it needs — mainly because of higher priorities and life stuff — but I've no plans to stop supporting it.
